# ----------------------- #
#      Main Configs       #
# ----------------------- #

 # Comment out url for development
# url: http://www.jbheron.com
title: Jess Heron
email: jessbheron@gmail.com
description: > # "Welcome to the personal website of Jess Heron. I work as a technical writer and content developer in SF. I hope you enjoy!"
# destination: ../jbheron.github.io

# For Testing 
destination: ../jbheron.github.io_testing

keep_files: [.git]
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: twitter
  #   url: https://twitter.com/jessbheron
  - title: github
    url: https://github.com/jbheron
  - title: linkedin
    url: https://linkedin.com/in/jessheron
